version: '3.8'

services:
  pgsql:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: manumafe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_repo
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/data/postgres
    networks:
      - app_network
  
  springapi:
    depends_on:
      - pgsql
    build: ./backend/book_repo
    container_name: spring-boot-api-container
    ports:
      - "8080:8080"
    networks:
      - app_network
  
  reactfrontend:
    depends_on:
      - springapi
    build: ./frontend/book_repo_frontend
    container_name: react-frontend-container
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  pgsql:

networks:
  app_network:
    name: app_network
